### ISSUE TITLE
Missing www.youtube-nocookie.com support

### ISSUE THREAD

**Issue by gangsthub** [vueframe/vueframe#2]
In https://github.com/vueframe/vueframe/blob/383bcd5866808255fac43a3270a6a7f58981e250/src/components/YouTube.vue#L41

You should allow a more privacy-friendly way of displaying Youtube videos. Important for GDPR and COPPA compliance according to their terms of service.

- https://support.google.com/youtube/answer/171780?hl=en
- https://support.google.com/policies/answer/9664901?sjid=6058548731349266559-EU

**Comment by GreenestGoat** [comment]
Thank you for bringing this to my attention! I've just implemented support for this feature for the V2 release. Which is a complete rebuild, and should be released by next week
